//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "measurement")]
pub enum Measurement {
  #[sea_orm(string_value = "grams")]
  Grams,
  #[sea_orm(string_value = "kilograms")]
  Kilograms,
  #[sea_orm(string_value = "litres")]
  Litres,
  #[sea_orm(string_value = "milligrams")]
  Milligrams,
  #[sea_orm(string_value = "millilitres")]
  Millilitres,
  #[sea_orm(string_value = "units")]
  Units,
}
