# fly.toml app configuration file generated for cilantrify on 2023-06-17T18:21:16+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cilantrify"
primary_region = "syd"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
